// <auto-generated />
using CraftShack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftShack.Migrations
{
    [DbContext(typeof(CraftShackDbContext))]
    [Migration("20251006081438_AddProductDescription")]
    partial class AddProductDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CraftShack.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A delicious cupcake inspired by Minecraft's Creeper.",
                            Name = "Creeper CupCake",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tasty steak with a Minecraft zombie twist.",
                            Name = "Zombie Steak",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet golden carrot candy for Minecraft fans.",
                            Name = "Golden Carrot Candy",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A shiny donut that looks like a Minecraft diamond.",
                            Name = "Diamond Donut",
                            Price = 4.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
